version: '3.8'

services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:latest
    container_name: masterchef-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: MASTERCHEF
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - masterchef-network

  # Aplicación Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masterchef-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/MASTERCHEF?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: MASTERCHEF
    depends_on:
      - mongodb
    networks:
      - masterchef-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  masterchef-network:
    driver: bridge
